### ISSUE TITLE
[Suggestion] Source link text and position

### ISSUE THREAD

**Issue by NathanBnm** [muriloventuroso/givemelyrics#13]
I thought that the source link will add the copyright of the song source like:

> © Artist label, year

And all of this as a link

Also I thought that it will not be always visible, but added at the end of the lyrics when scrolling, not at the bottom of the window.

**Comment by muriloventuroso** [comment]
I can not get the Copyright information from all sources correctly. But interesting the idea of putting the link at the end of the lyrics.

**Comment by NathanBnm** [comment]
##Source text

@muriloventuroso I don't know what the legal situation is. But maybe you can be more precise than just "Source" like:

> © Song title - Artist

If you can retrieve the year:

> © Song title - Artist, Year

And if there is different artists (like in feat.) don't know if you can retrieve the different names:

> © Song title - Artist 1 / Artist 2 / Artist 3, Year

##Concerning Letras

Maybe when the source is Letras you can redirect to the English version (https://www.letras.com/) instead of the Brazilian version (https://www.letras.mus.br/)
