### ISSUE TITLE
could you make a flatpak for givemelyrics?

### ISSUE THREAD

**Issue by chemel9** [muriloventuroso/givemelyrics#18]
Hi, I really appreciate your work , is a very good application
but i don't use elementary OS
could you make a flatpak for givemelyrics?
in this way, users can install the application in any linux distribution

please.
thank you.

**Comment by muriloventuroso** [comment]
It is in progress... :)

**Comment by muriloventuroso** [comment]
https://flathub.org/apps/details/com.github.muriloventuroso.givemelyrics
