### ISSUE TITLE
Change requested for AppCenter: OARS data

### ISSUE THREAD

**Issue by cassidyjames** [muriloventuroso/givemelyrics#2]
Thanks for your submission to AppCenter! However, during review we noticed an inaccuracy in your OARS content rating metadata: `social-info` is set to `none`, but your app connects to an online API. This means the level should be at least `mild`, depending on the amount of data sent.

Please resolve this issue and then submit a new release to AppCenter.

**Comment by muriloventuroso** [comment]
Okay. I'll find out about OARS content rating and update the information. Thank you!
