### ISSUE TITLE
The app is slower than before

### ISSUE THREAD

**Issue by NathanBnm** [muriloventuroso/givemelyrics#20]
Since last update the app takes more time to fetch the lyrics. This have an impact on synchronized lyrics which doesn't start at the beginning of the song.

Also "Loading..." doesn't appear anymore between songs. It's just stuck like 5 seconds on the previous song (or ad).

**Comment by muriloventuroso** [comment]
To get the letters synchronized, it is necessary to make 3 requests. So there may be some delay in loading the lyrics. This happens only if the synchronized letter option is active.
I'm working to add support for mobile versions of websites, they are lighter. And also looking for new sources.

**Comment by NathanBnm** [comment]
@muriloventuroso this seems to be fixed now.

**Comment by muriloventuroso** [comment]
Great!
