### ISSUE TITLE
[Suggestion] Adjust display

### ISSUE THREAD

**Issue by NathanBnm** [muriloventuroso/givemelyrics#21]
Maybe you should add a margin at the bottom on the window. It's looking a little strange that the scrolling bar is reaching the bottom of the screen I think.

Here is a screenshot:
![image](https://user-images.githubusercontent.com/45366162/51937591-545afc80-240b-11e9-9b2f-3b7b9c00dbc9.png)

Same for the lyrics:
![image](https://user-images.githubusercontent.com/45366162/51937650-6f2d7100-240b-11e9-9059-0fa285ea5854.png)

**Comment by muriloventuroso** [comment]
Good idea!
