### ISSUE TITLE
deepin-music's synchronized lyrics pool is quite a lot.

### ISSUE THREAD

**Issue by aasutossh** [muriloventuroso/givemelyrics#52]
I don't know what their source is, but it finds (synchronized)lyrics of most songs in my library.
They are [open-source](https://github.com/linuxdeepin/deepin-music) too.

**Comment by muriloventuroso** [comment]
Thanks for the tip

**Comment by aasutossh** [comment]
I'll try helping with once I am done with exams.

**Comment by muriloventuroso** [comment]
Any help is welcome

**Comment by aasutossh** [comment]
What?! Fixed already?
You are OP.
<3
